"""added category position

Revision ID: 0fa64aa52d22
Revises: f5d5c828f8cf
Create Date: 2025-09-03 15:41:03.697165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fa64aa52d22'
down_revision: Union[str, Sequence[str], None] = 'f5d5c828f8cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('position', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'position')
    # ### end Alembic commands ###
