"""added city position

Revision ID: 137daad6c222
Revises: 4cb940a53904
Create Date: 2025-09-03 00:17:58.160875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '137daad6c222'
down_revision: Union[str, Sequence[str], None] = '4cb940a53904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('position', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('city', 'position')
    # ### end Alembic commands ###
