"""added chat_id to user

Revision ID: a9cf8499c7fc
Revises: 4414af0cf676
Create Date: 2025-08-26 15:13:11.488823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9cf8499c7fc'
down_revision: Union[str, Sequence[str], None] = '4414af0cf676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('chat_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'chat_id')
    # ### end Alembic commands ###
