"""removed null photo

Revision ID: afb064452a62
Revises: 0fa64aa52d22
Create Date: 2025-09-03 16:37:19.084533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afb064452a62'
down_revision: Union[str, Sequence[str], None] = '0fa64aa52d22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flower', 'photo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('menu', 'photo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('panorama', 'photo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('restaurant', 'photo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant', 'photo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('panorama', 'photo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('menu', 'photo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('flower', 'photo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
