"""added flower currency

Revision ID: f5d5c828f8cf
Revises: 137daad6c222
Create Date: 2025-09-03 15:01:48.669527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d5c828f8cf'
down_revision: Union[str, Sequence[str], None] = '137daad6c222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flower', sa.Column('currency', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flower', 'currency')
    # ### end Alembic commands ###
